// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM1VPs5RwXUvaP4KWAGbWzQqLkrKzkgVs',
    appId: '1:244211951859:web:08f7d9d7ba2e3c17adaf86',
    messagingSenderId: '244211951859',
    projectId: 'mundialy-3e52b',
    authDomain: 'mundialy-3e52b.firebaseapp.com',
    storageBucket: 'mundialy-3e52b.firebasestorage.app',
    measurementId: 'G-V6YPQYL8Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfSFat1ofRk7ZW7Ju1P_WK8KsHWwxN5wg',
    appId: '1:244211951859:android:8244abcf53e810cdadaf86',
    messagingSenderId: '244211951859',
    projectId: 'mundialy-3e52b',
    storageBucket: 'mundialy-3e52b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj0Uir2Cm8BnSc6ofD4d_uR5gVlvaD1YI',
    appId: '1:244211951859:ios:d2aaca7faeb4cadbadaf86',
    messagingSenderId: '244211951859',
    projectId: 'mundialy-3e52b',
    storageBucket: 'mundialy-3e52b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj0Uir2Cm8BnSc6ofD4d_uR5gVlvaD1YI',
    appId: '1:244211951859:ios:d2aaca7faeb4cadbadaf86',
    messagingSenderId: '244211951859',
    projectId: 'mundialy-3e52b',
    storageBucket: 'mundialy-3e52b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM1VPs5RwXUvaP4KWAGbWzQqLkrKzkgVs',
    appId: '1:244211951859:web:8b3932d34d28fc00adaf86',
    messagingSenderId: '244211951859',
    projectId: 'mundialy-3e52b',
    authDomain: 'mundialy-3e52b.firebaseapp.com',
    storageBucket: 'mundialy-3e52b.firebasestorage.app',
    measurementId: 'G-3CKCZ0DNT1',
  );
}
