// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkfl5brFKzMufhuVcClgA86a4ewF_0l6I',
    appId: '1:578043250451:web:c30f6d26db0e93a5c57ce6',
    messagingSenderId: '578043250451',
    projectId: 'mundiali',
    authDomain: 'mundiali.firebaseapp.com',
    storageBucket: 'mundiali.firebasestorage.app',
    measurementId: 'G-N97HYHJ9TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8tivOuvf2RJMaATEFx8KGWBQ5pa9CKmA',
    appId: '1:578043250451:android:e8a7f88eddde04e9c57ce6',
    messagingSenderId: '578043250451',
    projectId: 'mundiali',
    storageBucket: 'mundiali.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIXz67DxP1SxGNRtF0pUHSPO4jg95vRjg',
    appId: '1:578043250451:ios:0efbd428477ce042c57ce6',
    messagingSenderId: '578043250451',
    projectId: 'mundiali',
    storageBucket: 'mundiali.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIXz67DxP1SxGNRtF0pUHSPO4jg95vRjg',
    appId: '1:578043250451:ios:0efbd428477ce042c57ce6',
    messagingSenderId: '578043250451',
    projectId: 'mundiali',
    storageBucket: 'mundiali.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkfl5brFKzMufhuVcClgA86a4ewF_0l6I',
    appId: '1:578043250451:web:9a5fc4ff18040a72c57ce6',
    messagingSenderId: '578043250451',
    projectId: 'mundiali',
    authDomain: 'mundiali.firebaseapp.com',
    storageBucket: 'mundiali.firebasestorage.app',
    measurementId: 'G-V2EMPV1SL4',
  );
}
