/// Code pays ISO 3166-1 alpha-3 (ex. ALG, FRA, ARG).
String resolveAlpha3Code(String? rawName, {String fallback = 'UNK'}) {
  final alpha2 = resolveCountryCode(rawName, fallback: '');
  if (alpha2.isEmpty || alpha2 == 'UN') {
    return fallback;
  }
  final base = alpha2.contains('-') ? alpha2.split('-').first : alpha2;
  return _alpha2ToAlpha3[base] ?? fallback;
}

String resolveCountryCode(String? rawName, {String fallback = 'UN'}) {
  if (rawName == null) return fallback;
  // If it's already a raw code like GB-ENG, pass it through directly
  final upper = rawName.trim().toUpperCase();
  if (upper.length <= 6 &&
      RegExp(r'^[A-Z]{2}(-[A-Z]{2,3})?$').hasMatch(upper)) {
    return upper;
  }

  // --- Arabic name lookup (before normalization which strips Arabic chars) ---
  final trimmed = rawName.trim();
  final arabicCode = _arabicCountryNames[trimmed];
  if (arabicCode != null) return arabicCode;

  final normalized = _normalizeCountryName(rawName);
  final mapped = _countryCodeByName[normalized];
  if (mapped != null) return mapped;

  // Partial / prefix match — handles truncated names like "Bosnia & Herzegovi..."
  for (final entry in _countryCodeByName.entries) {
    if (entry.key.length >= 4 && normalized.startsWith(entry.key)) {
      return entry.value;
    }
    if (entry.key.length >= 4 &&
        entry.key.startsWith(normalized) &&
        normalized.length >= 4) {
      return entry.value;
    }
  }

  if (RegExp(r'^[A-Z]{3}$').hasMatch(upper)) {
    final override = _alpha3ToFlagCodeOverrides[upper];
    if (override != null) return override;
    for (final entry in _alpha2ToAlpha3.entries) {
      if (entry.value == upper) return entry.key;
    }
    return fallback;
  }

  return fallback;
}

String _normalizeCountryName(String? value) {
  return (value ?? '')
      .trim()
      .toLowerCase()
      .replaceAll('ç', 'c') // curaçao → curacao
      .replaceAll('ô', 'o') // côte → cote
      .replaceAll('é', 'e')
      .replaceAll('è', 'e')
      .replaceAll('ê', 'e')
      .replaceAll('à', 'a')
      .replaceAll('â', 'a')
      .replaceAll('ü', 'u')
      .replaceAll('ö', 'o')
      .replaceAll('&', 'and')
      .replaceAll(
        RegExp(r"['\']"),
        ' ',
      ) // apostrophes → space: cote d'ivoire → cote d ivoire
      .replaceAll(RegExp(r'[^a-z0-9 -]'), '')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
}

const Map<String, String> _countryCodeByName = {
  // A
  'afghanistan': 'AF', 'albania': 'AL', 'algeria': 'DZ', 'andorra': 'AD',
  'angola': 'AO', 'antigua and barbuda': 'AG', 'argentina': 'AR',
  'armenia': 'AM', 'australia': 'AU', 'austria': 'AT', 'azerbaijan': 'AZ',
  // SofaScore aliases
  'ir iran': 'IR',
  'korea dpr': 'KP',
  'timor-leste': 'TL',
  'st kitts and nevis': 'KN', 'st lucia': 'LC',
  'saint kitts and nevis': 'KN',
  'brunei darussalam': 'BN', 'lao pdr': 'LA',
  'kyrgyz republic': 'KG',
  // B
  'bahamas': 'BS', 'bahrain': 'BH', 'bangladesh': 'BD', 'barbados': 'BB',
  'belarus': 'BY', 'belgium': 'BE', 'belize': 'BZ', 'benin': 'BJ',
  'bermuda': 'BM', 'bhutan': 'BT', 'bolivia': 'BO',
  'bosnia and herzegovina': 'BA',
  'bosnia herz': 'BA',
  'bosnia': 'BA',
  'bih': 'BA',
  'botswana': 'BW', 'brazil': 'BR', 'brunei': 'BN', 'bulgaria': 'BG',
  'burkina faso': 'BF', 'burundi': 'BI',
  // C
  'cabo verde': 'CV', 'cape verde': 'CV', 'cape verde islands': 'CV',
  'cambodia': 'KH', 'cameroon': 'CM', 'canada': 'CA',
  'central african republic': 'CF', 'chad': 'TD', 'chile': 'CL',
  'china': 'CN', 'china pr': 'CN', 'colombia': 'CO', 'comoros': 'KM',
  'comores': 'KM', 'comorian': 'KM',
  'congo': 'CG', 'congo dr': 'CD', 'dr congo': 'CD',
  'democratic republic of congo': 'CD', 'congo democratic republic': 'CD',
  'costa rica': 'CR', 'croatia': 'HR', 'cuba': 'CU', 'curacao': 'CW',
  'cyprus': 'CY', 'czech republic': 'CZ', 'czechia': 'CZ',
  'cote divoire': 'CI', 'cote d ivoire': 'CI', 'ivory coast': 'CI',
  // D
  'denmark': 'DK', 'djibouti': 'DJ', 'dominica': 'DM',
  'dominican republic': 'DO',
  // E
  'ecuador': 'EC', 'egypt': 'EG', 'el salvador': 'SV',
  'england': 'GB-ENG', 'eng': 'GB-ENG',
  'equatorial guinea': 'GQ', 'eritrea': 'ER', 'estonia': 'EE', 'ethiopia': 'ET',
  // F
  'faroe islands': 'FO', 'fiji': 'FJ', 'finland': 'FI', 'france': 'FR',
  // G
  'gabon': 'GA', 'gambia': 'GM', 'georgia': 'GE', 'germany': 'DE',
  'ghana': 'GH', 'greece': 'GR', 'grenada': 'GD', 'guatemala': 'GT',
  'guinea': 'GN', 'guineabissau': 'GW', 'guinea bissau': 'GW', 'guyana': 'GY',
  // H
  'haiti': 'HT', 'honduras': 'HN', 'hong kong': 'HK', 'hungary': 'HU',
  // I
  'iceland': 'IS', 'india': 'IN', 'indonesia': 'ID', 'iran': 'IR',
  'iraq': 'IQ', 'ireland': 'IE', 'israel': 'IL', 'italy': 'IT',
  // J
  'jamaica': 'JM', 'japan': 'JP', 'jordan': 'JO',
  // K
  'kazakhstan': 'KZ', 'kenya': 'KE', 'korea republic': 'KR',
  'south korea': 'KR', 'north korea': 'KP', 'kosovo': 'XK',
  'kuwait': 'KW', 'kyrgyzstan': 'KG',
  // L
  'laos': 'LA', 'latvia': 'LV', 'lebanon': 'LB', 'lesotho': 'LS',
  'liberia': 'LR', 'libya': 'LY', 'liechtenstein': 'LI',
  'lithuania': 'LT', 'luxembourg': 'LU',
  // M
  'macao': 'MO', 'madagascar': 'MG', 'malawi': 'MW', 'malaysia': 'MY',
  'maldives': 'MV', 'mali': 'ML', 'malta': 'MT', 'mauritania': 'MR',
  'mauritius': 'MU', 'mexico': 'MX', 'moldova': 'MD', 'mongolia': 'MN',
  'montenegro': 'ME', 'morocco': 'MA', 'maroc': 'MA', 'moroccan': 'MA',
  'marocaine': 'MA', 'marocain': 'MA', 'mozambique': 'MZ', 'myanmar': 'MM',
  'north macedonia': 'MK', 'macedonia': 'MK',
  // N
  'namibia': 'NA', 'nepal': 'NP', 'netherlands': 'NL', 'new zealand': 'NZ',
  'nicaragua': 'NI', 'niger': 'NE', 'nigeria': 'NG', 'norway': 'NO',
  'northern ireland': 'GB-NIR',
  // O
  'oman': 'OM',
  // P
  'pakistan': 'PK', 'palestine': 'PS', 'panama': 'PA', 'papua new guinea': 'PG',
  'paraguay': 'PY', 'peru': 'PE', 'philippines': 'PH', 'poland': 'PL',
  'portugal': 'PT', 'puerto rico': 'PR',
  // Q
  'qatar': 'QA',
  // R
  'romania': 'RO', 'russia': 'RU', 'rwanda': 'RW',
  // S
  'samoa': 'WS', 'san marino': 'SM', 'saudi arabia': 'SA',
  'scotland': 'GB-SCT', 'senegal': 'SN', 'serbia': 'RS', 'seychelles': 'SC',
  'sierra leone': 'SL', 'singapore': 'SG', 'slovakia': 'SK', 'slovenia': 'SI',
  'solomon islands': 'SB', 'somalia': 'SO', 'south africa': 'ZA',
  'south sudan': 'SS', 'spain': 'ES', 'sri lanka': 'LK', 'sudan': 'SD',
  'suriname': 'SR', 'eswatini': 'SZ', 'swaziland': 'SZ',
  'sweden': 'SE', 'switzerland': 'CH', 'syria': 'SY',
  // T
  'taiwan': 'TW', 'chinese taipei': 'TW', 'tajikistan': 'TJ',
  'tanzania': 'TZ', 'thailand': 'TH', 'timor leste': 'TL', 'togo': 'TG',
  'tonga': 'TO', 'trinidad and tobago': 'TT', 'tunisia': 'TN',
  'turkey': 'TR', 'turkiye': 'TR', 'turkmenistan': 'TM',
  // U
  'uae': 'AE', 'united arab emirates': 'AE', 'uganda': 'UG',
  'ukraine': 'UA', 'united kingdom': 'GB', 'uk': 'GB', 'united states': 'US',
  'usa': 'US', 'united states of america': 'US', 'uruguay': 'UY',
  'uzbekistan': 'UZ',
  // V
  'vanuatu': 'VU', 'venezuela': 'VE', 'vietnam': 'VN',
  'saint vincent and the grenadines': 'VC',
  // W
  'wales': 'GB-WLS',
  // Y
  'yemen': 'YE',
  // Z
  'zambia': 'ZM', 'zimbabwe': 'ZW',

  // Extra missing common aliases
  'holland': 'NL',
  'republic of ireland': 'IE',
  'drc': 'CD',
  'bosnia & herzegovina': 'BA',

  // 365Scores specific truncations/aliases (unique keys only)
  'bosnia and herz': 'BA',
  'bosnia & herz': 'BA',
  'bosnia herzeg': 'BA',
  'trinidad & tobago': 'TT',
  'st kitts': 'KN',
  'st. kitts': 'KN',
  'u.s. virgin islands': 'VI',
  'central african rep': 'CF',
  'equat. guinea': 'GQ',
  'sao tome': 'ST',
  'dem. rep. congo': 'CD',
  'fyr macedonia': 'MK',
  'rep. of ireland': 'IE',
  'türkiye': 'TR',

  // ── FRENCH TRANSLATIONS (WC 2022 & 2026) - only new keys not in English map ──
  'pays-bas': 'NL', 'pays bas': 'NL',
  'angleterre': 'GB-ENG',
  'etats-unis': 'US', 'etats unis': 'US', 'états-unis': 'US',
  'pays de galles': 'GB-WLS',
  'argentine': 'AR',
  'arabie saoudite': 'SA',
  'mexique': 'MX',
  'pologne': 'PL',
  'australie': 'AU',
  'danemark': 'DK',
  'tunisie': 'TN',
  'espagne': 'ES',
  'allemagne': 'DE',
  'japon': 'JP',
  'belgique': 'BE',
  'croatie': 'HR',
  'brésil': 'BR', 'bresil': 'BR',
  'serbie': 'RS',
  'suisse': 'CH',
  'cameroun': 'CM',
  // Note: 'ghana' already exists in English
  'corée du sud': 'KR', 'coree du sud': 'KR', 'corée': 'KR',
  'equateur': 'EC', 'équateur': 'EC',
  'sénégal': 'SN',
  // Note: 'france', 'senegal', 'maroc', 'portugal', 'canada', 'iran', 'ukraine', 'nigeria', 'costa rica' already in English map
  'russie': 'RU',
  'italie': 'IT',
  'autriche': 'AT',
  'suède': 'SE', 'suede': 'SE',
  'norvège': 'NO', 'norvege': 'NO',
  'finlande': 'FI',
  'grèce': 'GR', 'grece': 'GR',
  'turquie': 'TR',
  'roumanie': 'RO',
  'hongrie': 'HU',
  'slovaquie': 'SK',
  'slovénie': 'SI', 'slovenie': 'SI',
  'albanie': 'AL',
  'irak': 'IQ',
  'arabie': 'SA',
  'emirats arabes unis': 'AE', 'émirats arabes unis': 'AE',
  'chine': 'CN',
  'inde': 'IN',
  'afrique du sud': 'ZA',
  "cote d'ivoire": 'CI', "côte d'ivoire": 'CI',
  'nigéria': 'NG',
  'algérie': 'DZ', 'algerie': 'DZ',
  'égypte': 'EG', 'egypte': 'EG',
  'libye': 'LY',
  'éthiopie': 'ET',
  'ecosse': 'GB-SCT', 'écosse': 'GB-SCT',
  'irlande du nord': 'GB-NIR',
  'irlande': 'IE',
  'tchéquie': 'CZ',
  'tchequie': 'CZ',
  'republique tcheque': 'CZ',
  'république tchèque': 'CZ',
  'bosnie-herzégovine': 'BA',
  'bosnie': 'BA',
  'bosnie herzegovine': 'BA',
  'haïti': 'HT',
  'nouvelle-zélande': 'NZ', 'nouvelle zelande': 'NZ', 'nouvelle-zelande': 'NZ',
  'cap-vert': 'CV', 'cap vert': 'CV',
  'ouzbékistan': 'UZ', 'ouzbekistan': 'UZ',
  'colombie': 'CO',
  'curaçao': 'CW',
  'rd congo': 'CD', 'congo rd': 'CD', 'république démocratique du congo': 'CD',

  // ── ARABIC TRANSLATIONS (WC 2022 & 2026) ──
  'قطر': 'QA',
  'الإكوادور': 'EC', 'اكوادور': 'EC',
  'السنغال': 'SN',
  'هولندا': 'NL', 'هولاندا': 'NL',
  'إنجلترا': 'GB-ENG', 'انجلترا': 'GB-ENG',
  'إيران': 'IR', 'ايران': 'IR',
  'الولايات المتحدة': 'US', 'امريكا': 'US', 'أمريكا': 'US',
  'ويلز': 'GB-WLS',
  'الأرجنتين': 'AR', 'الارجنتين': 'AR',
  'السعودية': 'SA', 'المملكة العربية السعودية': 'SA',
  'المكسيك': 'MX',
  'بولندا': 'PL',
  'فرنسا': 'FR',
  'أستراليا': 'AU', 'استراليا': 'AU',
  'الدنمارك': 'DK',
  'تونس': 'TN',
  'إسبانيا': 'ES', 'اسبانيا': 'ES',
  'كوستاريكا': 'CR', 'كوستا ريكا': 'CR',
  'ألمانيا': 'DE', 'المانيا': 'DE',
  'اليابان': 'JP',
  'بلجيكا': 'BE',
  'كندا': 'CA',
  'المغرب': 'MA',
  'كرواتيا': 'HR',
  'البرازيل': 'BR',
  'صربيا': 'RS',
  'سويسرا': 'CH',
  'الكاميرون': 'CM',
  'غانا': 'GH',
  'كوريا الجنوبية': 'KR', 'كوريا': 'KR',
  'البرتغال': 'PT',
  'أوروجواي': 'UY', 'اوروجواي': 'UY',
  'اسكتلندا': 'GB-SCT', 'أسكتلندا': 'GB-SCT',
  'إيرلندا': 'IE', 'ايرلندا': 'IE',
  'روسيا': 'RU',
  'إيطاليا': 'IT', 'ايطاليا': 'IT',
  'النمسا': 'AT',
  'السويد': 'SE',
  'النرويج': 'NO',
  'فنلندا': 'FI',
  'اليونان': 'GR',
  'تركيا': 'TR',
  'رومانيا': 'RO',
  'المجر': 'HU',
  'أوكرانيا': 'UA', 'اوكرانيا': 'UA',
  'العراق': 'IQ',
  'الإمارات': 'AE', 'الامارات': 'AE',
  'الصين': 'CN',
  'الهند': 'IN',
  'جنوب أفريقيا': 'ZA',
  'ساحل العاج': 'CI',
  'نيجيريا': 'NG',
  'الجزائر': 'DZ',
  'مصر': 'EG',
  'ليبيا': 'LY',
  'إثيوبيا': 'ET', 'اثيوبيا': 'ET',
  'السودان': 'SD',
  'الأردن': 'JO',
  'فلسطين': 'PS',
  'لبنان': 'LB',
  'سوريا': 'SY',
  'إسرائيل': 'IL',
  'البحرين': 'BH',
  'الكويت': 'KW',
  'عُمان': 'OM', 'عمان': 'OM',
  'اليمن': 'YE',
};

const Map<String, String> _alpha2ToAlpha3 = {
  'AF': 'AFG',
  'AL': 'ALB',
  'DZ': 'ALG',
  'AD': 'AND',
  'AO': 'ANG',
  'AR': 'ARG',
  'AM': 'ARM',
  'AU': 'AUS',
  'AT': 'AUT',
  'AZ': 'AZE',
  'BS': 'BAH',
  'BH': 'BHR',
  'BD': 'BAN',
  'BB': 'BRB',
  'BY': 'BLR',
  'BE': 'BEL',
  'BZ': 'BLZ',
  'BJ': 'BEN',
  'BO': 'BOL',
  'BA': 'BIH',
  'BW': 'BOT',
  'BR': 'BRA',
  'BG': 'BUL',
  'BF': 'BFA',
  'BI': 'BDI',
  'CV': 'CPV',
  'KH': 'CAM',
  'CM': 'CMR',
  'CA': 'CAN',
  'CL': 'CHI',
  'CN': 'CHN',
  'CO': 'COL',
  'CG': 'CGO',
  'CD': 'COD',
  'CR': 'CRC',
  'CI': 'CIV',
  'HR': 'CRO',
  'CU': 'CUB',
  'CY': 'CYP',
  'CZ': 'CZE',
  'DK': 'DEN',
  'EC': 'ECU',
  'EG': 'EGY',
  'SV': 'SLV',
  'GQ': 'EQG',
  'EE': 'EST',
  'ET': 'ETH',
  'FI': 'FIN',
  'FR': 'FRA',
  'GA': 'GAB',
  'GM': 'GAM',
  'DE': 'GER',
  'GH': 'GHA',
  'GR': 'GRE',
  'GT': 'GUA',
  'GN': 'GUI',
  'HT': 'HAI',
  'HN': 'HON',
  'HU': 'HUN',
  'IS': 'ISL',
  'IN': 'IND',
  'ID': 'IDN',
  'IR': 'IRN',
  'IQ': 'IRQ',
  'IE': 'IRL',
  'IL': 'ISR',
  'IT': 'ITA',
  'JM': 'JAM',
  'JP': 'JPN',
  'JO': 'JOR',
  'KZ': 'KAZ',
  'KE': 'KEN',
  'KP': 'PRK',
  'KR': 'KOR',
  'KW': 'KUW',
  'LV': 'LVA',
  'LB': 'LBN',
  'LY': 'LBY',
  'LT': 'LTU',
  'LU': 'LUX',
  'MG': 'MAD',
  'MW': 'MAW',
  'MY': 'MAS',
  'ML': 'MLI',
  'MT': 'MLT',
  'MR': 'MTN',
  'MX': 'MEX',
  'MD': 'MDA',
  'ME': 'MNE',
  'MA': 'MAR',
  'MZ': 'MOZ',
  'NL': 'NED',
  'NZ': 'NZL',
  'NI': 'NCA',
  'NG': 'NGA',
  'MK': 'MKD',
  'NO': 'NOR',
  'OM': 'OMA',
  'PA': 'PAN',
  'PY': 'PAR',
  'PE': 'PER',
  'PH': 'PHI',
  'PL': 'POL',
  'PT': 'POR',
  'QA': 'QAT',
  'RO': 'ROU',
  'RU': 'RUS',
  'SA': 'KSA',
  'SN': 'SEN',
  'RS': 'SRB',
  'SL': 'SLE',
  'SG': 'SIN',
  'SK': 'SVK',
  'SI': 'SVN',
  'ZA': 'RSA',
  'ES': 'ESP',
  'SE': 'SWE',
  'CH': 'SUI',
  'SY': 'SYR',
  'TZ': 'TAN',
  'TH': 'THA',
  'TG': 'TOG',
  'TT': 'TRI',
  'TN': 'TUN',
  'TR': 'TUR',
  'UG': 'UGA',
  'UA': 'UKR',
  'AE': 'UAE',
  'US': 'USA',
  'UY': 'URU',
  'UZ': 'UZB',
  'VE': 'VEN',
  'VN': 'VIE',
  'YE': 'YEM',
  'ZM': 'ZAM',
  'ZW': 'ZIM',
  'GB': 'ENG',
  'NC': 'NCL',
  'TW': 'TPE',
  'PS': 'PLE',
};

const Map<String, String> _alpha3ToFlagCodeOverrides = {
  'COM': 'KM',
  'ENG': 'GB-ENG',
  'NIR': 'GB-NIR',
  'SCO': 'GB-SCT',
  'WAL': 'GB-WLS',
};

/// Arabic team/country name → ISO-2 code
const Map<String, String> _arabicCountryNames = {
  'الأرجنتين': 'AR',
  'أرجنتين': 'AR',
  'أستراليا': 'AU',
  'استراليا': 'AU',
  'النمسا': 'AT',
  'أذربيجان': 'AZ',
  'ألبانيا': 'AL',
  'الجزائر': 'DZ',
  'جزائر': 'DZ',
  'أفغانستان': 'AF',
  'أنغولا': 'AO',
  'أرمينيا': 'AM',
  'إريتريا': 'ER',
  'إثيوبيا': 'ET',
  'إكوادور': 'EC',
  'إندونيسيا': 'ID',
  'أيرلندا': 'IE',
  'إيرلندا': 'IE',
  'إيران': 'IR',
  'ايران': 'IR',
  'العراق': 'IQ',
  'عراق': 'IQ',
  'الأردن': 'JO',
  'أردن': 'JO',
  'أوروغواي': 'UY',
  'أوروجواي': 'UY',
  'أوزبكستان': 'UZ',
  'أيسلندا': 'IS',
  'إسبانيا': 'ES',
  'اسبانيا': 'ES',
  'إسرائيل': 'IL',
  'إيطاليا': 'IT',
  'ايطاليا': 'IT',
  'البرازيل': 'BR',
  'برازيل': 'BR',
  'بلجيكا': 'BE',
  'البلجيك': 'BE',
  'البرتغال': 'PT',
  'برتغال': 'PT',
  'بلغاريا': 'BG',
  'بوليفيا': 'BO',
  'البوسنة والهرسك': 'BA',
  'البوسنة': 'BA',
  'بوسنة': 'BA',
  'بوركينا فاسو': 'BF',
  'بنما': 'PA',
  'بيرو': 'PE',
  'بيلاروسيا': 'BY',
  'البحرين': 'BH',
  'بحرين': 'BH',
  'بنغلاديش': 'BD',
  'باراغواي': 'PY',
  'باراجواي': 'PY',
  'باكستان': 'PK',
  'البنين': 'BJ',
  'بولندا': 'PL',
  'بريطانيا': 'GB',
  'تركيا': 'TR',
  'تونس': 'TN',
  'تايلاند': 'TH',
  'تنزانيا': 'TZ',
  'تشاد': 'TD',
  'تشيكيا': 'CZ',
  'جمهورية التشيك': 'CZ',
  'تشيلي': 'CL',
  'شيلي': 'CL',
  'الجابون': 'GA',
  'جابون': 'GA',
  'جنوب أفريقيا': 'ZA',
  'جنوب افريقيا': 'ZA',
  'جنوب السودان': 'SS',
  'جامايكا': 'JM',
  'جورجيا': 'GE',
  'جيبوتي': 'DJ',
  'جمهورية الكونغو الديمقراطية': 'CD',
  'الدنمارك': 'DK',
  'دنمارك': 'DK',
  'رواندا': 'RW',
  'روسيا': 'RU',
  'رومانيا': 'RO',
  'الإمارات': 'AE',
  'الإمارات العربية المتحدة': 'AE',
  'امارات': 'AE',
  'السعودية': 'SA',
  'العربية السعودية': 'SA',
  'المملكة العربية السعودية': 'SA',
  'سوريا': 'SY',
  'السودان': 'SD',
  'سودان': 'SD',
  'الصومال': 'SO',
  'صومال': 'SO',
  'السنغال': 'SN',
  'سنغال': 'SN',
  'سويسرا': 'CH',
  'السويد': 'SE',
  'سويد': 'SE',
  'سلوفاكيا': 'SK',
  'سلوفينيا': 'SI',
  'سيراليون': 'SL',
  'سريلانكا': 'LK',
  'صربيا': 'RS',
  'عُمان': 'OM',
  'عمان': 'OM',
  'غانا': 'GH',
  'غواتيمالا': 'GT',
  'غينيا': 'GN',
  'فرنسا': 'FR',
  'فنلندا': 'FI',
  'فنزويلا': 'VE',
  'فيتنام': 'VN',
  'الفلبين': 'PH',
  'فلسطين': 'PS',
  'قطر': 'QA',
  'قبرص': 'CY',
  'قيرغيزستان': 'KG',
  'الكاميرون': 'CM',
  'كاميرون': 'CM',
  'الكويت': 'KW',
  'كويت': 'KW',
  'كرواتيا': 'HR',
  'كندا': 'CA',
  'كولومبيا': 'CO',
  'كوريا الجنوبية': 'KR',
  'كوريا': 'KR',
  'كوريا الشمالية': 'KP',
  'كوسوفو': 'XK',
  'كوستاريكا': 'CR',
  'كوستا ريكا': 'CR',
  'الكونغو': 'CG',
  'كونغو': 'CG',
  'كينيا': 'KE',
  'كازاخستان': 'KZ',
  'كوت ديفوار': 'CI',
  'ساحل العاج': 'CI',
  'لبنان': 'LB',
  'ليبيا': 'LY',
  'لوكسمبورغ': 'LU',
  'ليتوانيا': 'LT',
  'لاتفيا': 'LV',
  'المغرب': 'MA',
  'مغرب': 'MA',
  'مصر': 'EG',
  'المكسيك': 'MX',
  'مكسيك': 'MX',
  'ملاوي': 'MW',
  'مالي': 'ML',
  'ماليزيا': 'MY',
  'مالطا': 'MT',
  'موريتانيا': 'MR',
  'موزمبيق': 'MZ',
  'مقدونيا الشمالية': 'MK',
  'مقدونيا': 'MK',
  'المملكة المتحدة': 'GB',
  'نيجيريا': 'NG',
  'نيجريا': 'NG',
  'النرويج': 'NO',
  'نرويج': 'NO',
  'نيبال': 'NP',
  'نيكاراغوا': 'NI',
  'نيوزيلندا': 'NZ',
  'هولندا': 'NL',
  'هولاندا': 'NL',
  'هنغاريا': 'HU',
  'هندوراس': 'HN',
  'الهند': 'IN',
  'ويلز': 'GB-WLS',
  'اليابان': 'JP',
  'يابان': 'JP',
  'اليمن': 'YE',
  'يمن': 'YE',
  'إنجلترا': 'GB-ENG',
  'انجلترا': 'GB-ENG',
  'إسكتلندا': 'GB-SCT',
  'اسكتلندا': 'GB-SCT',
  'أيرلندا الشمالية': 'GB-NIR',
  'الولايات المتحدة': 'US',
  'الولايات المتحدة الأمريكية': 'US',
  'امريكا': 'US',
  'أمريكا': 'US',
  'ألمانيا': 'DE',
  'المانيا': 'DE',
  'هايتي': 'HT',
  'الرأس الأخضر': 'CV',
  'كابو فيردي': 'CV',
  'كوراساو': 'CW',
  'الكونغو الديمقراطية': 'CD',
};
