String resolveCountryCode(String? rawName, {String fallback = 'UN'}) {
  final normalized = _normalizeCountryName(rawName);
  return _countryCodeByName[normalized] ?? fallback;
}

String _normalizeCountryName(String? value) {
  return (value ?? '')
      .trim()
      .toLowerCase()
      .replaceAll('&', 'and')
      .replaceAll(RegExp(r'[^a-z0-9 ]'), '')
      .replaceAll(RegExp(r'\s+'), ' ');
}

const Map<String, String> _countryCodeByName = {
  'albania': 'AL',
  'argentina': 'AR',
  'austria': 'AT',
  'australia': 'AU',
  'bosnia and herzegovina': 'BA',
  'bih': 'BA',
  'belgium': 'BE',
  'bulgaria': 'BG',
  'bolivia': 'BO',
  'brazil': 'BR',
  'belarus': 'BY',
  'bosnia herz': 'BA',
  'bosnia': 'BA',
  'cameroon': 'CM',
  'canada': 'CA',
  'cape verde': 'CV',
  'cape verde islands': 'CV',
  'china pr': 'CN',
  'china': 'CN',
  'czech republic': 'CZ',
  'czechia': 'CZ',
  'curacao': 'CW',
  'costa rica': 'CR',
  'croatia': 'HR',
  'dr congo': 'CD',
  'congo dr': 'CD',
  'democratic republic of congo': 'CD',
  'congo democratic republic': 'CD',
  'dominican republic': 'DO',
  'denmark': 'DK',
  'el salvador': 'SV',
  'eng': 'GB',
  'ecuador': 'EC',
  'england': 'GB',
  'finland': 'FI',
  'france': 'FR',
  'georgia': 'GE',
  'germany': 'DE',
  'ghana': 'GH',
  'guatemala': 'GT',
  'haiti': 'HT',
  'honduras': 'HN',
  'hungary': 'HU',
  'iceland': 'IS',
  'iraq': 'IQ',
  'iran': 'IR',
  'israel': 'IL',
  'japan': 'JP',
  'jamaica': 'JM',
  'jordan': 'JO',
  'kazakhstan': 'KZ',
  'kuwait': 'KW',
  'mali': 'ML',
  'mexico': 'MX',
  'morocco': 'MA',
  'netherlands': 'NL',
  'new zealand': 'NZ',
  'north macedonia': 'MK',
  'norway': 'NO',
  'oman': 'OM',
  'panama': 'PA',
  'paraguay': 'PY',
  'philippines': 'PH',
  'poland': 'PL',
  'portugal': 'PT',
  'qatar': 'QA',
  'russia': 'RU',
  'saudi arabia': 'SA',
  'slovakia': 'SK',
  'slovenia': 'SI',
  'senegal': 'SN',
  'serbia': 'RS',
  'sweden': 'SE',
  'syria': 'SY',
  'south korea': 'KR',
  'korea republic': 'KR',
  'spain': 'ES',
  'switzerland': 'CH',
  'trinidad and tobago': 'TT',
  'tunisia': 'TN',
  'uae': 'AE',
  'united arab emirates': 'AE',
  'uzbekistan': 'UZ',
  'united states': 'US',
  'usa': 'US',
  'uruguay': 'UY',
  'venezuela': 'VE',
  'vietnam': 'VN',
  'wales': 'GB',
  'algeria': 'DZ',
  'egypt': 'EG',
  'italy': 'IT',
  'colombia': 'CO',
  'chile': 'CL',
  'peru': 'PE',
  'nigeria': 'NG',
  'ivory coast': 'CI',
  'cote divoire': 'CI',
  'south africa': 'ZA',
  'greece': 'GR',
  'turkiye': 'TR',
  'turkey': 'TR',
  'romania': 'RO',
  'ukraine': 'UA',
  'scotland': 'GB',
  'ireland': 'IE',
  'northern ireland': 'GB',
};
