import '../models/live_match.dart';

List<LiveMatch> getMockMatches() {
  return [
    const LiveMatch(
      id: 'mock-1',
      dateLabel: 'Mon 20 Nov',
      localTime: '18:00 local',
      city: 'Doha',
      homeTeam: 'Qatar',
      homeCode: 'QTR',
      homeTeamId: 1569,
      awayTeam: 'Ecuador',
      awayCode: 'ECA',
      awayTeamId: 2382,
      phaseLabel: 'Group A',
      source: MatchDataSource.mock,
      scoreHome: 0,
      scoreAway: 2,
      isLive: false,
    ),
    const LiveMatch(
      id: 'mock-2',
      dateLabel: 'Tue 21 Nov',
      localTime: '21:00 local',
      city: 'Lusail',
      homeTeam: 'England',
      homeCode: 'ENG',
      homeTeamId: 10,
      awayTeam: 'Iran',
      awayCode: 'IRN',
      awayTeamId: 30,
      phaseLabel: 'Group B',
      source: MatchDataSource.mock,
      scoreHome: 6,
      scoreAway: 2,
      isLive: true,
    ),
    const LiveMatch(
      id: 'mock-3',
      dateLabel: 'Wed 22 Nov',
      localTime: '17:00 local',
      city: 'Al Rayyan',
      homeTeam: 'Argentina',
      homeCode: 'AR',
      homeTeamId: 26,
      awayTeam: 'Saudi Arabia',
      awayCode: 'SA',
      awayTeamId: 28,
      phaseLabel: 'Group C',
      source: MatchDataSource.mock,
      scoreHome: 1,
      scoreAway: 2,
      isLive: false,
    ),
    const LiveMatch(
      id: 'mock-final',
      dateLabel: 'Sun 18 Dec',
      localTime: '18:00 local',
      city: 'Lusail',
      homeTeam: 'Argentina',
      homeCode: 'AR',
      homeTeamId: 26,
      awayTeam: 'France',
      awayCode: 'FR',
      awayTeamId: 2,
      phaseLabel: 'Final',
      source: MatchDataSource.mock,
      scoreHome: 3,
      scoreAway: 3,
      penaltyHome: 4,
      penaltyAway: 2,
      isLive: false,
    ),
  ];
}
