name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_and_analyze:
    name: Code Analysis & Testing
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: flutter_application_1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Code Formatting
        run: dart format --set-exit-if-changed lib/ || true

      - name: Static Analysis
        run: flutter analyze || true

      - name: Run Tests
        run: flutter test --coverage

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: flutter_application_1/coverage/lcov.info
